name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  APP_ENV: dev
  APP_HOST: 0.0.0.0
  APP_PORT: 3000
  APP_URL: http://localhost:3000
  DB_HOST: localhost
  DB_USER: postgres
  DB_PASSWORD: thisisasamplepassword
  DB_NAME: go-starter
  DB_PORT: 5432
  # JWT Config
  JWT_SECRET: test-secret-key-for-ci
  JWT_ACCESS_EXP_MINUTES: 30
  JWT_REFRESH_EXP_DAYS: 30
  JWT_RESET_PASSWORD_EXP_MINUTES: 10
  JWT_VERIFY_EMAIL_EXP_MINUTES: 10
  # SMTP Config (dummy for CI)
  SMTP_HOST: localhost
  SMTP_PORT: 587
  SMTP_USERNAME: test
  SMTP_PASSWORD: test
  EMAIL_FROM: test@example.com

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: thisisasamplepassword
          POSTGRES_DB: go-starter
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: go.sum

      - name: Verify dependencies
        run: |
          go mod download
          go mod verify

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres > /dev/null 2>&1; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Attempt $i: PostgreSQL not ready yet..."
            sleep 2
          done

      - name: Test database connection
        run: |
          PGPASSWORD=thisisasamplepassword psql -h localhost -U postgres -d go-starter -c "SELECT version();"

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
        env:
          APP_ENV: ${{ env.APP_ENV }}
          APP_HOST: ${{ env.APP_HOST }}
          APP_PORT: ${{ env.APP_PORT }}
          APP_URL: ${{ env.APP_URL }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_PORT: ${{ env.DB_PORT }}
          JWT_SECRET: ${{ env.JWT_SECRET }}
          JWT_ACCESS_EXP_MINUTES: ${{ env.JWT_ACCESS_EXP_MINUTES }}
          JWT_REFRESH_EXP_DAYS: ${{ env.JWT_REFRESH_EXP_DAYS }}
          JWT_RESET_PASSWORD_EXP_MINUTES: ${{ env.JWT_RESET_PASSWORD_EXP_MINUTES }}
          JWT_VERIFY_EMAIL_EXP_MINUTES: ${{ env.JWT_VERIFY_EMAIL_EXP_MINUTES }}
          SMTP_HOST: ${{ env.SMTP_HOST }}
          SMTP_PORT: ${{ env.SMTP_PORT }}
          SMTP_USERNAME: ${{ env.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ env.SMTP_PASSWORD }}
          EMAIL_FROM: ${{ env.EMAIL_FROM }}

      - name: Build application
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/main ./src
        env:
          APP_ENV: ${{ env.APP_ENV }}
          APP_HOST: ${{ env.APP_HOST }}
          APP_PORT: ${{ env.APP_PORT }}
          APP_URL: ${{ env.APP_URL }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_PORT: ${{ env.DB_PORT }}
          JWT_SECRET: ${{ env.JWT_SECRET }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
        continue-on-error: true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-starter-binary
          path: bin/main
          retention-days: 7