name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  APP_ENV: dev
  APP_HOST: 0.0.0.0
  APP_PORT: 3000
  APP_URL: http://localhost:3000
  DB_HOST: localhost
  DB_USER: postgres
  DB_PASSWORD: thisisasamplepassword
  DB_NAME: go-starter
  DB_PORT: 5432
  JWT_SECRET: test-secret-key-for-ci

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: go.sum

      - name: Verify dependencies
        run: |
          go mod download
          go mod verify

      - name: Build application
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/main ./src
        env:
          APP_ENV: ${{ env.APP_ENV }}
          APP_HOST: ${{ env.APP_HOST }}
          APP_PORT: ${{ env.APP_PORT }}
          APP_URL: ${{ env.APP_URL }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_PORT: ${{ env.DB_PORT }}
          JWT_SECRET: ${{ env.JWT_SECRET }}

      - name: Check binary size
        run: |
          ls -lh bin/main
          echo "Binary size: $(du -h bin/main | cut -f1)"

      - name: Verify binary is executable
        run: |
          chmod +x bin/main
          file bin/main

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-starter-binary-${{ github.sha }}
          path: bin/main
          retention-days: 7
          compression-level: 9

      - name: Create build summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Build completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Build Details:**" >> $GITHUB_STEP_SUMMARY
          echo "- Go Version: $(go version)" >> $GITHUB_STEP_SUMMARY
          echo "- Binary Size: $(du -h bin/main | cut -f1)" >> $GITHUB_STEP_SUMMARY
          echo "- OS: linux" >> $GITHUB_STEP_SUMMARY
          echo "- Architecture: amd64" >> $GITHUB_STEP_SUMMARY
          echo "- Commit SHA: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY